# Generated by Django 4.2.6 on 2023-11-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_user_biography_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='thought',
            field=models.ManyToManyField(blank=True, related_name='likes', to='blog.thought'),
        ),
    ]
